<script setup lang="ts">
/**
 * Guida di «Registra passaggio»: che cosa fa il programma quando cambia il titolare di un'unità, e
 * che cosa **non** decide al posto dell'amministratore.
 *
 * Testi dal §2 e dal §6 di `docs/pertinenze_vendita_locazione.md` e dalle decisioni 11–20 del
 * progetto sul subentro. Ogni sentenza citata è verificata su fonte (17–18/09/2026): la 9148/2008
 * **non** è il criterio della delibera, la 24654/2010 sì; l'attestazione dell'art. 1130 n. 9 la
 * chiede il condòmino e non ha valore liberatorio (Cass. 7260/2024).
 */
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { ArrowRightLeft, BookOpen, CalendarDays, Landmark, Scale, ScrollText, ShieldCheck, Undo2 } from 'lucide-vue-next';

defineProps<{ open: boolean }>();
defineEmits(['update:open']);
</script>

<template>
  <Sheet :open="open" @update:open="$emit('update:open', $event)">
    <SheetContent class="sm:max-w-2xl overflow-y-auto w-full sm:w-[600px] p-0">
      <div class="px-6 py-8">
        <SheetHeader class="mb-8">
          <div class="flex items-center gap-3 mb-2">
            <div class="p-2 bg-indigo-100 text-indigo-700 rounded-lg dark:bg-indigo-900 dark:text-indigo-300">
              <BookOpen class="w-6 h-6" />
            </div>
            <SheetTitle class="text-2xl font-extrabold tracking-tight">Guida: registrare un passaggio</SheetTitle>
          </div>
          <SheetDescription class="text-base text-slate-600 dark:text-slate-400">
            Vendita, donazione, locazione, usufrutto, successione: come il programma conserva la storia dell'unità e cosa mostra prima di scrivere.
          </SheetDescription>
        </SheetHeader>

        <div class="space-y-8 text-sm text-slate-700 dark:text-slate-300">

          <section>
            <h3 class="flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-white mb-3">
              <ArrowRightLeft class="w-5 h-5 text-indigo-500" /> Chi esce, chi entra
            </h3>
            <p class="mb-3">
              «Registra passaggio» <strong>chiude</strong> il periodo di chi esce al giorno prima della data dell'atto e <strong>apre</strong> quello di chi entra da quella data. La riga di chi esce non sparisce: resta nello storico dell'unità, con le sue date, perché il riparto e l'estratto conto l'hanno già raccontata.
            </p>
            <p class="mb-3">
              È diverso da «Modifica associazione», che corregge un dato sbagliato sulla stessa persona, e da «Dissocia», che cancella una riga scritta per errore. Una riga con una storia — un periodo chiuso, un passaggio registrato — non si cancella e non si sovrascrive con un'altra persona: il programma lo rifiuta e rimanda qui.
            </p>
            <p class="text-[13px] text-slate-500 dark:text-slate-400">
              La locazione <strong>si aggiunge</strong>, non sostituisce: il proprietario resta, l'inquilino entra con il suo ruolo. Verso il condominio continua a rispondere il proprietario; all'inquilino vengono addebitate solo le voci il cui coefficiente lo indica.
            </p>
          </section>

          <section>
            <h3 class="flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-white mb-3">
              <CalendarDays class="w-5 h-5 text-indigo-500" /> Da quando
            </h3>
            <p class="mb-3">
              Si scrive <strong>una data sola</strong>, quella dell'atto. Il giorno prima lo calcola il programma: chiedere due date è l'errore che produce buchi e sovrapposizioni. Sotto il campo compare la frase che dice esattamente chi risulterà titolare fino a quando e chi da quando.
            </p>
            <p class="mb-3">
              La data non ha un valore predefinito. «Oggi» è il giorno in cui si compila, quasi mai il giorno del rogito: il programma non tira a indovinare una data che decide chi paga.
            </p>
            <p class="text-[13px] text-slate-500 dark:text-slate-400">
              Per lo straordinario conta la data della delibera che ha approvato lavori e prezzo, non quella del passaggio (Cass. 24654/2010; art. 63 disp. att. c.c.): l'obbligazione è sorta con la delibera, e resta di chi era titolare allora. Per l'ordinario la spesa matura nel tempo e si divide in proporzione ai giorni.
            </p>
          </section>

          <section>
            <h3 class="flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-white mb-3">
              <Scale class="w-5 h-5 text-indigo-500" /> Cosa cambia nei conti
            </h3>
            <p class="mb-3">
              Il pannello «Cosa cambierà» è calcolato dal server su quello che hai scritto e si aggiorna mentre compili. Quattro blocchi: l'anagrafica, le rate già emesse e il conguaglio, chi resta obbligato, cosa non cambia.
            </p>
            <ul class="list-disc pl-5 space-y-2 mb-3">
              <li><strong>Le rate già emesse non si toccano.</strong> Sono crediti già iscritti verso persone nominate. Il conguaglio si propone come righe di saldo di segno opposto che sommano zero, una coppia per ogni persona che entra: di solito credito a chi esce e debito a chi entra, o viceversa.</li>
              <li><strong>La morosità resta di chi l'ha maturata.</strong> Il conguaglio si calcola sulla competenza, non sui pagamenti.</li>
              <li><strong>Nella vendita le rate in bozza passano a chi entra.</strong> Se il piano ha già una quota a giornale, o un incasso, un credito usato o un rimborso su una sua quota, o se un passaggio non annullato, anche su un'altra unità, l'ha già preso nel suo conguaglio, non si ricalcola più, e il passaggio lo prende nel suo conguaglio: le rate in bozza che scadono dal giorno del passaggio passano a chi entra — cambia l'intestatario, non l'importo — e il conguaglio è la sua parte dell'intero piano meno quelle rate (se le rate coprono più dei suoi giorni, si rovescia). Restano a chi esce, e si conguagliano, le bozze già scadute o pagate e quelle di una straordinaria che è sua; il saldo pregresso dentro una bozza resta suo in una quota a parte. Se chi vende tiene un'altra parte dell'unità — per esempio è proprietario pieno di metà e usufruttuario dell'altra metà, e vende la metà piena — passa solo la spesa della quota che esce: le bozze, che comprendono anche la parte che resta, restano a chi vende, e la parte che passa si conguaglia. Il pannello dice quali rate passano e quali no, e perché. Se invece il piano si ricalcola ancora e le parti si sono accordate che le sue rate le paga chi vende, il piano si ricalcola comunque per giorni: verso il condominio le rate dal giorno dell'atto sono di chi compra, e i pagamenti di chi vende si registrano con «Versato da», che resta scritto su entrambi gli estratti conto.</li>
              <li><strong>Il conguaglio segue ogni quota lungo i passaggi.</strong> Quando sulla stessa unità i passaggi si susseguono — chi vende e poi ricompra, chi compra e rivende, un usufrutto che finisce e una nuda proprietà che passa di mano — il programma non guarda il ruolo che una persona ha oggi, ma da quale quota viene ogni rata già emessa e dove quella quota è arrivata. Chi entra paga solo i giorni della quota che gli arriva, anche se chi esce ha avuto o tiene altre quote sulla stessa unità; le rate di una parte che chi esce ha già ceduto con un passaggio precedente, o che non gli è mai arrivata, restano a chi le ha ricevute, e il pannello lo dice. Un esempio, su una spesa di € 1.200,00 l'anno: Ugo vende a Bice il 1° marzo, Bice rivende a Ugo il 1° maggio, Ugo vende a Carlo il 1° luglio, con le rate emesse fra un passaggio e l'altro. Il conguaglio di ogni passaggio si calcola, e sommando rate e conguagli ognuno paga i suoi giorni da titolare: Ugo € 394,52 (120 giorni), Bice € 200,55 (61 giorni), Carlo € 604,93 (184 giorni).</li>
              <li><strong>Quando il conguaglio si ferma.</strong> Se non sa separare con certezza la parte che passa, il conguaglio non propone cifre e lo dice nel pannello («le quote sono passate per più strade»), con la ragione e il passaggio in causa: dove il dato manca il programma non tira a indovinare. Succede:
                <ul class="list-disc pl-5 space-y-1.5 mt-2">
                  <li>quando, in una catena di passaggi, il piano non dice da quale riga di titolarità viene una quota, o la riga è stata cambiata a mano dopo la generazione, senza un passaggio che dica come. I piani generati o ricalcolati prima della 1.11.0-beta.43 non portano il dato: il programma lo ricava dove la riga è una sola, e si ferma dove ce n'è più d'una (chi ha venduto e ricomprato prima della generazione). Un piano senza dettaglio del riparto si ferma anche su un'unità mista la cui titolarità è cambiata dopo la generazione;</li>
                  <li>quando un passaggio registrato prima della 1.11.0-beta.43 ha preso il piano senza scrivere nessuna coppia di conguaglio su questa unità: con le versioni precedenti il conguaglio poteva essersi fermato e le parti averlo regolato a mano, e il programma non può saperlo. Dove la quota attraversa quel passaggio cambiando persona e la catena è ambigua, il conguaglio si ferma e dice quale passaggio; un passaggio che ha scritto la sua coppia sull'unità non ferma niente;</li>
                  <li>quando una nuda proprietà è nata da una somma dopo la generazione del piano ed è tornata piena solo in parte: chi era già nudo proprietario compra un'altra nuda, o riceve una riserva d'usufrutto, a piano già generato; poi un'estinzione fa tornare piena una parte soltanto, e dopo c'è un altro passaggio. Le rate emesse stanno sulla nuda sommata, e il programma non sa quali sono della parte tornata piena e quali di quella rimasta nuda: se una quota di una persona arriva su quella nuda proprietà, si ferma il conguaglio di tutto il gruppo di quote di quella persona sul piano e sull'unità, anche quando la persona è chi esce. Non si ferma ciò che la legge del passaggio esclude per intero: l'ordinaria nella vendita con riserva d'usufrutto, se si è scelta la legge, e la straordinaria nella costituzione e nell'estinzione dell'usufrutto. Se la somma è precedente alla generazione del piano — il caso comune dei genitori che hanno donato con riserva anni prima — il conguaglio si calcola;</li>
                  <li>con le quote della 1.7.x, quando il piano ha assorbito un saldo pregresso.</li>
                </ul>
                <span class="block mt-2">In ognuno di questi casi, se serve un conguaglio, si scrive con un saldo manuale dal Wallet sulla stessa gestione.</span></li>
              <li><strong>Nella locazione e nell'usufrutto le bozze restano a chi esce</strong> e il conguaglio le comprende (alla fine di una locazione senza un nuovo inquilino il conguaglio non c'è: qui sotto). Alla costituzione dell'usufrutto il modulo chiede chi paga l'ordinaria dal giorno dell'atto, come nella riserva (qui sotto). Nella vendita della nuda proprietà l'ordinaria dei piani generati prima dell'usufrutto è dell'usufruttuario (art. 1004 c.c.) e non passa a chi compra la nuda proprietà, salvo le voci che sono del nudo proprietario perché alla costituzione o alla riserva hai scelto «come dice ogni voce». Se il piano si ricalcola ancora (niente a giornale, nessun movimento e nessun passaggio che l'abbia preso nel suo conguaglio), il passaggio lo lascia al ricalcolo, e ricalcolato le rate passano da sé, salvo le voci che il passaggio non ha potuto spostare (qui sotto). Dopo una vendita o un usufrutto il programma chiede di ricalcolarlo prima di emettere o di registrare un incasso; dopo un cambio d'inquilino no, e un piano emesso senza ricalcolo lascia le quote all'inquilino di prima.</li>
              <li><strong>La locazione su un piano che non si ricalcola più.</strong> Le quote del piano restano a chi le ha, emesse o no. Alla fine di una locazione senza un nuovo inquilino non c'è conguaglio: le quote non ancora emesse restano a chi esce, e chi paga i giorni dopo l'uscita lo decide l'amministratore; nei piani generati o ricalcolati dopo il passaggio le voci a carico dell'inquilino vanno a chi le riceve nel riparto, come dice la voce sull'«Inquilino» (guida «Ruoli e usufrutto»), e il pannello lo nomina. All'inizio di una locazione la parte del nuovo inquilino dal giorno del contratto resta nelle quote di chi le paga, e il nuovo inquilino la rimborsa con il prospetto degli oneri accessori: il pannello lo dice piano per piano, e unità per unità quando le pertinenze hanno storie diverse. Con un nuovo inquilino al posto di quello che esce, invece, il conguaglio dà a chi entra i suoi giorni.</li>
              <li><strong>Il passaggio porta tutta la quota di chi esce.</strong> Se l'atto trasferisce solo una parte della quota, il passaggio non si registra da qui: si registra a mano. Chiudi la riga di chi vende al giorno prima dell'atto da «Modifica associazione», poi da «Associa soggetto» riapri chi vende alla quota che tiene e apri chi compra alla sua, tutte e due dal giorno dell'atto. Non c'è conguaglio automatico. Con le date attaccate il riparto conta le righe nuove dal giorno dell'atto; con un buco fra le date valgono da sempre, e un piano generato o ricalcolato dopo le addebita anche per i mesi prima dell'atto.</li>
              <li><strong>Il piano preso dal conguaglio resta com'è.</strong> Non si ricalcola, non si elimina e non perde una voce. Lo stesso per il piano tenuto fermo da una successione con il conguaglio non scritto: il messaggio lo dice. Annullare il conguaglio dallo storico vuol dire che le parti hanno regolato fra loro, e il piano resta fermo (un'eccezione per i passaggi registrati prima della 1.11.0-beta.42: se il passaggio aveva preso il piano solo per rate segnate «emesse» senza scritture, annullato il conguaglio il piano non è più fermo, e va ricalcolato prima di emettere o di registrare un incasso); per ricalcolarlo si tolgono prima le sue quote a giornale e i movimenti, se ne ha, poi si annulla il passaggio dallo storico della sua unità, lo si registra di nuovo e si ricalcola (con un passaggio registrato prima della versione 1.11.0-beta.42 l'ordine lo dicono i messaggi). Se le parti avevano già regolato fra loro, il messaggio lo dice, con la cifra quando la rinuncia o l'annullamento del conguaglio sono fatti dalla versione 1.11.0-beta.42 in poi: ricalcolando, il condominio addebita a chi entra i suoi giorni, e quell'accordo va rifatto. Un movimento tolto si registra di nuovo dopo il ricalcolo.</li>
              <li><strong>Nella vendita o donazione con riserva d'usufrutto chi vende resta usufruttuario</strong>, sulla stessa quota, e il modulo chiede chi paga l'ordinaria dal giorno dell'atto. La proposta è la legge: l'usufruttuario (art. 1004 c.c.). Allora nelle rate già emesse e nelle bozze dei piani che hanno già emesso l'ordinaria resta a chi vende e non si conguaglia, e le voci ordinarie sul «Proprietario» — anche quelle senza coefficienti — passano sull'«Usufruttuario», così un piano generato o ricalcolato dopo l'atto fa lo stesso, salvo la spesa addebitata direttamente all'unità, che non ha una voce e va al nudo proprietario. Le voci sono elencate tutte spuntate: togli la spunta a quelle che devono andare al nudo proprietario. Non si spostano le voci di una gestione che ha un piano approvato: quelle che il piano elenca hanno la ripartizione bloccata, e un piano senza capitoli le comprende tutte. Se quel piano non si ricalcola più (ha una quota a giornale, un incasso, un credito usato o un rimborso su una sua quota, o è già stato preso nel conguaglio di un passaggio), per quel piano non serve spostarle: l'ordinaria è già dell'usufruttuario anche sulle quote ancora in bozza (nella costituzione gliela dà il conguaglio, nella riserva resta a chi vende e non si conguaglia). Se si ricalcola ancora, la scelta non lo raggiunge: non c'è conguaglio, e il piano generato o ricalcolato dà l'ordinaria di quelle voci al nudo proprietario. Per applicarla, riporta il piano in bozza dalla sua pagina prima di registrare il passaggio, poi riapprovalo e ricalcolalo. Il pannello dice quale caso è, con il nome del piano; una voce bloccata da più piani di casi diversi ha una frase sua, senza rimedio. Le voci create dopo partono dal «Proprietario». La scelta resta scritta nello storico del passaggio. Una voce vale per tutta la tabella, e il modulo elenca le altre unità in usufrutto che lo spostamento tocca; dove non c'è usufrutto paga il proprietario, come prima. Con «come dice ogni voce» le voci non si toccano e il conguaglio le segue una per una: le voci sul «Proprietario», e l'addebito diretto all'unità, passano a chi compra la nuda proprietà per i giorni dopo l'atto. Se chi vende ha solo una quota e sull'unità resta un altro proprietario pieno, il programma divide l'unità secondo le quote registrate (guida «Ruoli e usufrutto»); i saldi pregressi intestati all'unità, per ora, no. Le straordinarie seguono la competenza — la data della delibera, o quella dichiarata sulla fattura — come in ogni vendita, e dal giorno dell'atto sono del nudo proprietario (art. 1005 c.c.). Si dichiara spuntando «Chi vende o dona resta usufruttuario»: il programma non la deduce dal ruolo scelto.</li>
              <li><strong>Millesimi, tabelle e pertinenze non cambiano.</strong> Il collegamento di una pertinenza è descrittivo e non sposta importi.</li>
              <li><strong>Il prospetto degli oneri accessori.</strong> Dalla pagina dei titolari, il pulsante con la stampante («Prospetto oneri accessori» sugli schermi larghi) stampa per ogni conduttore le voci che il riparto pone a carico dell'inquilino, divise per giorni di conduzione, e accanto a ogni voce come è pagata: «nelle sue rate», se è già intestata a lui; «con il conguaglio del cambio d'inquilino del …», se un cambio d'inquilino registrato dopo la generazione del piano gli ha dato quei giorni con il conguaglio; «pagata da …», se l'ha pagata un titolare perché in quei giorni nessun inquilino era registrato, ed è la parte da rimborsare. È sul preventivo; il conguaglio definitivo si fa sul rendiconto.</li>
            </ul>
            <p class="text-[13px] text-slate-500 dark:text-slate-400">
              Se il passaggio tocca rate già emesse o cambia il destinatario di un piano già generato, la conferma chiede una spunta e una nota di almeno dieci caratteri, che restano registrate con l'operazione. Se non tocca nulla, il pulsante è attivo subito. Le quote che restano a chi le ha — per legge o per la scelta fatta nel modulo, come l'ordinaria che resta all'usufruttuario e la straordinaria che resta al nudo proprietario, o perché a chi entra non ne va nessuna parte, come quelle di soli saldi pregressi o di una spesa tutta di chi vende — il modulo le elenca sopra il pulsante, senza chiedere la spunta: il passaggio non le tocca.
            </p>
          </section>

          <section>
            <h3 class="flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-white mb-3">
              <Landmark class="w-5 h-5 text-indigo-500" /> Quando finisce un usufrutto
            </h3>
            <p class="mb-3">
              L'estinzione si registra da «Registra passaggio», scegliendo «Usufrutto» e poi «Estinzione»: la riga dell'usufruttuario si chiude al giorno prima dell'atto e il nudo proprietario dell'usufrutto che finisce torna <strong>proprietario pieno</strong> dal giorno dell'atto. Le rate già emesse non si toccano: per le voci che spettavano all'usufruttuario il conguaglio scrive un credito a chi esce e un debito a chi torna proprietario pieno, per i giorni dopo l'atto. La scheda «Chi torna proprietario pieno» e il pannello «Cosa cambierà» dicono chi sono.
            </p>
            <ul class="list-disc pl-5 space-y-2 mb-3">
              <li><strong>Senza un altro usufrutto in corso tutti i nudi proprietari tornano proprietari pieni</strong>, ciascuno per la sua quota. Se chi esce è anche nudo proprietario di una parte — per esempio ha comprato la nuda proprietà mentre era usufruttuario — torna proprietario pieno anche per quella: le sue quote dal giorno dell'atto restano a suo nome, senza un conguaglio con la stessa persona, e il pannello lo dice. Con più nudi proprietari il conguaglio si divide fra loro. Un esempio, su una voce di € 1.200,00 l'anno sull'«Usufruttuario»: Ugo ha l'usufrutto di tutta l'unità e la nuda proprietà di metà, Mara la nuda proprietà dell'altra metà. Finito l'usufrutto il 1° aprile restano 275 giorni, € 904,11: € 452,06 restano a Ugo e € 452,05 passano a Mara, e il credito di Ugo scende a € 452,05.</li>
              <li><strong>Con un altro usufrutto in corso sull'unità</strong> — per esempio due usufrutti sulle due metà, o due genitori usufruttuari — <strong>torna proprietario pieno solo il nudo proprietario dell'usufrutto che finisce</strong>. Gli altri nudi proprietari restano nudi, sotto l'usufrutto che continua, e chi esce non torna nudo proprietario dell'altra parte: se tutti tornassero proprietari pieni, le quote dell'unità sommerebbero più del 100 %. Il programma lo decide da sé quando i dati lo dicono: se l'usufrutto viene da una costituzione o da una vendita con riserva registrate da qui, lo dice il passaggio da cui è nato l'usufrutto, anche dopo che la nuda proprietà è stata venduta; se i nudi proprietari che possono tornare proprietari pieni valgono insieme proprio la quota dell'usufrutto, tornano loro; se un solo nudo proprietario vale più dell'usufrutto — due genitori donano con riserva al figlio, poi muore uno dei due — torna proprietario pieno solo per la parte dell'usufrutto che finisce e resta nudo proprietario del resto, e la sua riga si divide in due (è la regola di legge quando l'atto non dice altro). Con l'usufrutto di ciascun genitore al 50 %, su una voce di € 1.200,00 sull'«Usufruttuario» il figlio torna proprietario pieno per il 50 % e resta nudo proprietario dell'altro 50 %, sotto l'usufrutto di chi sopravvive; il conguaglio dei 275 giorni dal 1° aprile è di € 452,05, a debito del figlio e a credito di chi esce. Lo stesso quando quella nuda proprietà, dopo, è passata a più persone con una successione registrata da qui (anche se poi un erede ha venduto la sua parte): gli eredi l'hanno ricevuta in comune, e la parte dell'usufrutto che finisce torna piena a ciascuno per la sua quota, senza che la scheda chieda niente. Se invece un testamento o una divisione hanno dato a ciascun erede la nuda proprietà di una parte precisa, l'estinzione si registra a mano da «Modifica associazione».</li>
              <li><strong>Quando i dati non bastano, sceglie l'amministratore.</strong> Con usufrutti censiti a mano, o con nudi proprietari che valgono più dell'usufrutto che finisce — fuori dal caso degli eredi di una nuda proprietà sola, qui sopra —, la scheda «Chi torna proprietario pieno» chiede quali nudi proprietari tornano proprietari pieni, e non preseleziona niente. Si spuntano i nudi della parte su cui l'usufrutto finisce: insieme devono valere proprio la quota dell'usufrutto, altrimenti il programma rifiuta e lo dice. Un esempio: Ugo ed Elsa hanno l'usufrutto di una metà a testa, Mara la nuda proprietà della metà di Ugo e Carlo quella della metà di Elsa. Finisce l'usufrutto di Ugo: si spunta Mara, che torna proprietario pieno, Carlo resta nudo proprietario sotto l'usufrutto di Elsa, e il conguaglio dei 275 giorni dal 1° aprile è di € 452,05, a debito di Mara e a credito di Ugo (voce di € 1.200,00 sull'«Usufruttuario»). C'è anche la casella «Tutti i nudi proprietari, ciascuno per la sua quota», da usare se la nuda proprietà è in comune fra i nudi proprietari — per esempio una donazione ai due figli con la riserva d'usufrutto per i due genitori: ogni nudo proprietario torna proprietario pieno per la sua parte dell'usufrutto che finisce e resta nudo proprietario del resto (due figli al 50 % sotto due usufrutti del 50 %: ciascuno torna proprietario pieno per il 25 % e resta nudo proprietario per il 25 %), e il conguaglio si divide come dice il pannello. Se nessun insieme di nudi interi vale l'usufrutto (nudi al 75 % e al 25 % sotto due usufrutti del 50 %), le caselle dei nudi non compaiono e resta solo quella per quota.</li>
              <li><strong>Quando il programma si ferma.</strong> In alcuni casi il programma non sa quale nuda proprietà torna piena, e rifiuta l'estinzione: il messaggio dice la ragione. Succede:
                <ul class="list-disc pl-5 space-y-1.5 mt-2">
                  <li>con un altro usufrutto in corso, quando chi esce ha anche una nuda proprietà che può essere quella della parte su cui l'usufrutto finisce — comprata mentre era usufruttuario, o indicata dal passaggio da cui l'usufrutto è nato —: il programma non sa quale nuda proprietà torna piena;</li>
                  <li>con un altro usufrutto in corso, quando i nudi proprietari che possono tornare proprietari pieni valgono meno dell'usufrutto che finisce: una parte della nuda proprietà può essere di chi esce, o mancare fra le righe in corso;</li>
                  <li>quando la nuda proprietà che tornerebbe piena solo in parte è nata proprio il giorno dell'estinzione: il programma non scrive, nello stesso giorno, la nuda proprietà e il suo consolidamento, cioè la parte che ne torna piena;</li>
                  <li>quando due estinzioni cadono lo stesso giorno sulle stesse righe (due genitori che muoiono lo stesso giorno): la seconda trova la nuda proprietà e la proprietà piena della stessa persona nate lo stesso giorno, e non le può riunire. Qui il programma non indica una strada: le righe si correggono a mano da «Modifica associazione», o si chiede assistenza;</li>
                  <li>quando una pertinenza spuntata ha anch'essa un altro usufrutto: se lì serve una scelta, si toglie la spunta e l'estinzione si registra dalla pertinenza, dove si sceglie; se lì il programma si ferma, si toglie la spunta e la pertinenza si registra a mano da «Modifica associazione».</li>
                </ul>
                <span class="block mt-2">Nei primi tre casi l'estinzione si registra <strong>a mano</strong>: da «Modifica associazione» si chiude la riga dell'usufrutto al giorno prima dell'atto e si correggono le righe dei nudi proprietari secondo l'atto. Non c'è conguaglio automatico: se serve, si scrive con un saldo manuale dal Wallet sulla stessa gestione. Se invece l'atto prevede che l'usufrutto si accresca all'altro usufruttuario, vale il punto qui sotto.</span></li>
              <li><strong>L'accrescimento.</strong> Con un altro usufruttuario in corso, la scheda offre la casella «L'usufrutto si accresce all'altro usufruttuario»: va spuntata quando l'atto lo prevede, o quando l'usufrutto è un legato a più persone insieme (artt. 675 e 678 c.c.). Allora l'usufrutto di chi muore va agli usufruttuari che restano, in proporzione alla loro quota, la nuda proprietà resta nuda e il conguaglio dell'ordinaria va a loro. Senza la spunta, negli atti fra vivi, vale la regola di legge quando l'atto non dice altro: la nuda proprietà si riunisce all'usufrutto che finisce. Nel legato di usufrutto congiunto è la legge stessa a portare all'accrescimento: la casella va spuntata. Se la nuda proprietà dell'unità è di più nudi proprietari, la casella non c'è, e l'accrescimento si registra a mano da «Modifica associazione»: con nude proprietà di origini diverse il programma non sa quale usufrutto stia sopra quale nuda; con gli eredi di una nuda proprietà sola la nuda è in comune, e senza la spunta torna piena a ciascuno per la sua quota, salvo quando chi esce ha anche una nuda proprietà: allora il programma si ferma anche senza la spunta (vedi «Quando il programma si ferma»), e l'estinzione si registra a mano.</li>
              <li><strong>Chi resta obbligato.</strong> Il blocco «Chi resta obbligato» del pannello dice chi risponde delle spese. Se sull'unità non resta nessun altro titolare, chi torna proprietario pieno risponde di tutte le spese dell'unità (se sono più d'uno, ciascuno per la sua quota). Se ne restano — un altro usufrutto con i suoi nudi proprietari, il proprietario pieno dell'altra metà nell'unità mista — o se la nuda proprietà torna piena solo in parte, chi torna proprietario pieno risponde della parte dell'usufrutto che finisce (se sono più d'uno, ciascuno per la sua parte), e del resto dell'unità rispondono, come prima, i titolari di quella parte, chi torna pieno compreso se ne resta nudo proprietario: dove resta un usufrutto, il nudo proprietario e l'usufruttuario in solido (art. 67 ult. co. disp. att. c.c.). Per i passaggi registrati dalla 1.11.0-beta.43 in poi lo storico del passaggio dice anche chi torna proprietario pieno e per quale parte.</li>
            </ul>
            <p class="text-[13px] text-slate-500 dark:text-slate-400">
              Il modulo guarda le righe in corso il giorno dell'estinzione, non quelle di oggi: un'estinzione registrata in ritardo si sceglie sui nudi proprietari di allora. Se cambi chi esce o la data, la scelta si azzera e va rifatta.
            </p>
          </section>

          <!-- 1.11.0-beta.44, decisioni 64–66: la successione. -->
          <section>
            <h3 class="flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-white mb-3">
              <ScrollText class="w-5 h-5 text-indigo-500" /> Quando muore un proprietario
            </h3>
            <p class="mb-3">
              Si registra da «Registra passaggio» scegliendo «Successione», o dal menu della riga del titolare con «Registra la successione». Vale per il proprietario pieno, il comproprietario e il nudo proprietario; la morte dell'usufruttuario è l'estinzione dell'usufrutto, quella dell'inquilino la fine della locazione.
            </p>
            <ul class="list-disc pl-5 space-y-2 mb-3">
              <li><strong>Una data sola, quella del decesso.</strong> Gli eredi sono titolari da quel giorno, nello stesso ruolo del defunto, e il defunto fino al giorno prima. La data in cui lo studio lo sa e quella della dichiarazione di successione non spostano niente: si registra quando gli eredi si fanno avanti, anche mesi dopo.</li>
              <li><strong>Gli eredi, ognuno con la sua quota</strong> dell'unità: insieme fanno la quota del defunto. «Dividi in parti uguali» la divide al centesimo di punto. Un erede che era già comproprietario somma la quota ereditata alla sua. Un erede minorenne si registra come gli altri: verso il condominio paga, con i beni dell'erede, chi ne ha la rappresentanza.</li>
              <li><strong>Le rate in bozza</strong> di un piano che non si ricalcola più passano a un erede solo, l'erede di riferimento, che il modulo chiede solo quando serve: cambia l'intestatario, non l'importo. Un piano che si ricalcola ancora, ricalcolato, dà da sé i giorni dopo il decesso agli eredi per quota.</li>
              <li><strong>Il conguaglio si sceglie.</strong> Con l'arretrato a nome del defunto, se il conguaglio ha righe da proporre, il pannello «Cosa cambierà» chiede se scriverlo, senza niente di già scelto. «Scrivi il conguaglio»: è quello della vendita, i giorni dopo il decesso sono degli eredi, divisi per quota, con righe di saldo per ciascuno; la parte dell'erede di riferimento scende dell'importo delle rate in bozza che riceve. «Non scriverlo: la posizione resta com'è»: nessuna riga in saldi, le rate emesse restano al defunto e le bozze dell'elenco del pannello passano all'erede di riferimento, che le paga tutte (restano al defunto, come nella vendita, quelle già scadute o pagate e quelle di una straordinaria che era sua); non chiede di dichiarare un accordo, e la nota è facoltativa. Con l'arretrato agli eredi la scelta non c'è: conguaglio e arretrato fanno un conto solo. Vale anche per il legato.</li>
              <li><strong>Il nudo proprietario.</strong> Se il defunto era nudo proprietario, l'usufrutto resta com'è e gli eredi prendono il suo posto: la straordinaria segue la delibera o la competenza dichiarata sulla fattura, l'ordinaria segue la voce. Le voci ordinarie sul «Proprietario» erano a suo carico e passano agli eredi; la legge (art. 1004 c.c.) le darebbe all'usufruttuario, e per i piani che verranno la si segue spostando la voce su «Usufruttuario», che vale per tutta la tabella.</li>
              <li><strong>L'arretrato del defunto</strong> (le rate emesse e non pagate, le sue bozze, i suoi saldi) è la sua posizione verso il condominio: se è un debito, ne risponde ogni erede per la sua quota (art. 754 c.c.); può anche essere un credito, se il defunto aveva versato in più. Dove scriverlo è una scelta dello studio. Si può passarlo agli eredi per quota, con righe di saldo sulla stessa gestione: con il conguaglio ogni erede risponde della sua quota di tutto, e la posizione del defunto si chiude. In quel caso le rate in bozza dei piani che non si ricalcolano più, anche quelle di prima del decesso, vanno all'erede di riferimento, salvo quelle con un pagamento, e la parte degli altri eredi si regola con le loro righe di saldo, del conguaglio e dell'arretrato, che entrano nel prossimo piano della stessa gestione; le rate già emesse al defunto restano a suo nome e non si incassano, perché il loro importo è già nelle righe degli eredi. Si può invece lasciarlo a nome del defunto («eredi di …») e chiederlo agli eredi, registrando chi versa con «Versato da». Le quote che un piano ricalcolato dopo dà al defunto per i giorni prima del decesso l'arretrato non le comprende, e il riquadro «Da sapere» lo dice: con l'arretrato agli eredi si passano agli eredi con un saldo manuale dal Wallet; con l'arretrato a nome del defunto restano a suo nome.</li>
              <li><strong>Il legato.</strong> Se il testamento lascia l'unità a chi non eredita il patrimonio, si spunta «L'unità è un legato»: chi riceve l'unità paga dal giorno del decesso, e l'arretrato del defunto resta a suo nome, perché ne rispondono gli eredi.</li>
              <li><strong>Niente copia autentica.</strong> La casella della vendita libera chi vende (art. 63 co. 5 disp. att. c.c.) e qui non c'entra; al suo posto si può allegare la dichiarazione di successione o il testamento.</li>
              <li><strong>Se il defunto era anche usufruttuario dell'unità</strong> e il suo usufrutto risulta ancora in corso il giorno del decesso, la successione si ferma: l'usufrutto si estingue con la morte (art. 979 c.c.) e non passa agli eredi. Si registra prima «Usufrutto → estinzione» con la stessa data, poi la successione. Vale anche per una pertinenza spuntata.</li>
              <li><strong>Correggere.</strong> Con l'arretrato agli eredi il conguaglio e l'arretrato fanno un conto solo: non si annulla il solo conguaglio, si annulla il passaggio e lo si registra di nuovo. Con l'arretrato a nome del defunto il conguaglio scritto si annulla come nella vendita, e annullarlo vuol dire che le parti hanno regolato fra loro; se invece non andava scritto, si annulla il passaggio e lo si registra di nuovo con «Non scriverlo».</li>
            </ul>
          </section>

          <section>
            <h3 class="flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-white mb-3">
              <ShieldCheck class="w-5 h-5 text-indigo-500" /> Chi resta obbligato
            </h3>
            <p class="mb-3">
              Chi acquista risponde in solido con chi vende per i contributi dell'esercizio in corso e di quello precedente (art. 63 co. 4 disp. att. c.c.). Il programma <strong>non intesta nulla</strong> all'acquirente per questo, salvo i saldi intestati all'unità, che si addebitano quando si genera il piano: la nota resta nel pannello e nella situazione debitoria dell'unità. Chi paga in forza della solidarietà ha regresso verso il venditore per quanto ha pagato al condominio, salvo diverso accordo fra le parti (Cass. 11199/2021).
            </p>
            <p class="mb-3">
              Finché il condominio non riceve <strong>copia autentica del titolo</strong>, chi vende resta obbligato per i contributi maturati dopo (art. 63 co. 5). La casella «Ho ricevuto copia autentica del titolo», con la sua data, è l'unico campo del modulo con un effetto giuridico diretto. Registra pure il passaggio anche senza: l'anagrafe si aggiorna sulla comunicazione scritta del condòmino (art. 1130 n. 6 c.c.).
            </p>
            <p class="mb-3">
              Nella <strong>vendita o donazione con riserva d'usufrutto</strong>, dal giorno dell'atto nudo proprietario e usufruttuario rispondono in solido verso il condominio (art. 67 ult. co. disp. att. c.c.), e la copia autentica non libera chi vende, che resta usufruttuario. Se chi compra la nuda proprietà risponda anche dell'arretrato di chi vende (art. 63 co. 4) la giurisprudenza non l'ha chiarito: decide l'amministratore.
            </p>
            <p class="mb-3">
              Nella <strong>successione</strong>, dei contributi maturati fino al giorno prima del decesso rispondono gli eredi, ognuno in proporzione della sua quota ereditaria (art. 754 c.c.); dal decesso gli eredi rispondono dei contributi dell'unità come comproprietari, divisi fra loro per quota, e in assemblea li rappresenta una persona sola (art. 67 co. 2 disp. att. c.c.).
            </p>
            <p class="text-[13px] text-slate-500 dark:text-slate-400">
              L'attestazione dello stato dei pagamenti e delle liti in corso (art. 1130 n. 9 c.c.) la chiede il condòmino che vende; il notaio la pretende nella prassi, ma non ha valore liberatorio verso il condominio (Cass. 7260/2024).
            </p>
          </section>

          <!-- 1.11.0-beta.37, decisione 27: l'annullamento dell'ultimo passaggio, a rate intatte. -->
          <section>
            <h3 class="flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-white mb-3">
              <Undo2 class="w-5 h-5 text-indigo-500" /> Ho registrato un passaggio sbagliato
            </h3>
            <p class="mb-3">
              Si annulla dallo storico dell'unità: nella pagina dei titolari il pulsante «Storico» apre «Chi ha avuto questa unità», e sotto il passaggio c'è «Annulla il passaggio…». Le pertinenze passate insieme all'unità tornano con lei, nella stessa operazione: nello storico della pertinenza quel passaggio non compare. Prima di confermare il programma dice che cosa torna come prima — le righe di titolarità scritte dal passaggio, le quote delle rate passate a chi era entrato — e, se c'è, che il conguaglio si toglie dai saldi della gestione; e dice che cosa resta da fare, per esempio ricalcolare di nuovo un piano generato o ricalcolato dopo il passaggio. Serve una nota di almeno dieci caratteri, che resta nello storico.
            </p>
            <p class="mb-3">
              Si annulla <strong>solo l'ultimo passaggio</strong> dell'unità, e solo <strong>a rate intatte</strong>. Altrimenti, al posto del comando compare «Annulla il passaggio — non consentito: perché?», e con un clic si legge che cosa sistemare prima. Succede quando:
            </p>
            <ul class="list-disc pl-5 space-y-2 mb-3">
              <li>sull'unità, o su una pertinenza passata con lei, c'è un passaggio con una data successiva, o con la stessa data e registrato dopo: si annulla prima quello;</li>
              <li>una rata passata a chi era entrato è stata emessa; oppure sulla quota dell'unità in quella rata c'è un pagamento, anche solo sulla parte del saldo pregresso rimasta a chi era uscito; oppure chi era entrato o chi era uscito ha segnalato dal portale un pagamento di quella rata, non ancora verificato;</li>
              <li>in un piano generato o ricalcolato dopo il passaggio, una quota che l'annullamento cambierebbe — di chi era entrato, di chi era uscito o di chi ha preso i giorni rimasti scoperti — è stata emessa o pagata, o ne è stato segnalato il pagamento dal portale e non è ancora verificato;</li>
              <li>il conguaglio è già stato assorbito da un piano;</li>
              <li>una riga di titolarità aperta, chiusa o cambiata dal passaggio è stata corretta a mano dopo;</li>
              <li>una riga associata o modificata a mano dopo il passaggio si scontra con quella che tornerebbe: la stessa persona, nello stesso ruolo, due volte nello stesso periodo, oppure quote dello stesso ruolo oltre 100 nello stesso giorno. Il «perché?» dice come sistemarla.</li>
            </ul>
            <p class="mb-3">
              Il passaggio annullato resta nello storico, con la data, chi l'ha annullato e la nota; nessun conto lo legge più.
            </p>
            <p class="text-[13px] text-slate-500 dark:text-slate-400">
              Un passaggio registrato prima della 1.11.0-beta.37 non si annulla: il programma non teneva il registro di ciò che scriveva. Si corregge a mano, chiudendo la riga con una data di fine e registrando da «Associa soggetto» la titolarità giusta.
            </p>
          </section>

        </div>
      </div>
    </SheetContent>
  </Sheet>
</template>
